services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ny_taxi || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    depends_on:
      - pgdatabase

  ingest:
    build: .
    depends_on:
      pgdatabase:
        condition: service_healthy
    # ENTRYPOINT đã là ["python","ingest_data.py"], nên command chỉ cần args
    command:
      [
        "--user=root",
        "--password=root",
        "--host=pgdatabase",
        "--port=5432",
        "--db=ny_taxi",
        "--table_name=yellow_taxi_trips",
        "--url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz"
      ]
    # (tuỳ chọn) mount thư mục hiện tại nếu bạn muốn ghi log/file ra ngoài
    # volumes:
    #   - .:/app

volumes:
  db_data:
